### ISSUE TITLE
How can I set OIDC User or Group

### ISSUE THREAD

**Issue by hsok85** [alphagov/terraform-provider-concourse#15]

**Comment by yashbhutwala** [comment]
+1 is this possible?

**Comment by yashbhutwala** [comment]
I would like to do this for generic oauth: https://concourse-ci.org/generic-oauth.html.  Here is how I manage it currently without terraform...

```yaml
roles:
- name: owner
  oauth:
    users:
    - USER1
```
